#ifndef JCONFIG_H
#define JCONFIG_H

#define JPEG_LIB_VERSION 62
#define LIBJPEG_TURBO_VERSION "3.0.3"
#define LIBJPEG_TURBO_VERSION_NUMBER 3000003
#define C_ARITH_CODING_SUPPORTED 1
#define D_ARITH_CODING_SUPPORTED 1
#define MEM_SRCDST_SUPPORTED 1

#ifndef BITS_IN_JSAMPLE
#define BITS_IN_JSAMPLE 8
#endif

#endif /* JCONFIG_H */
